CREATE DATABASE LAPTOPS;
USE LAPTOPS;

CREATE TABLE LAPT1(LAP_ID INT PRIMARY KEY,
BRAND VARCHAR(50),
LAP_TYPE VARCHAR(50),
INCHES VARCHAR(20),
SCREEN_RESOLUTION VARCHAR(100),
CPU VARCHAR(100),
RAM VARCHAR(50),
MEMORY VARCHAR(50),
GPU VARCHAR(100),
OS VARCHAR(50),
WEIGHT VARCHAR(50),
PRICE DECIMAL(15,2));

LOAD DATA INFILE 'C:\\ProgramData\\MySQL\\MySQL Server 8.0\\Uploads\\laptopData_ROWS_CLEANED.csv'
INTO TABLE LAPT1
FIELDS TERMINATED BY ',' 
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES;

/* DATA CLEANING

1. REMOVE DUPLICATES
2. FORMATING
3. DATA NORMALIZATION
4. REMOVE UNNECESSARY COLUMNS
*/

-- 1. DATA CLEANING 

-- IMPORTANT NOTE ALWAYS CREATE A DUPLICATE TABLE TO ALTER THE DATA DO MOT EDIT THE ORIGINAL DATA 

SELECT *,ROW_NUMBER() OVER (PARTITION BY LAP_ID)
FROM LAPT1;

CREATE TABLE `lapt2` (
  `LAP_ID` int NOT NULL,
  `BRAND` varchar(50) DEFAULT NULL,
  `LAP_TYPE` varchar(50) DEFAULT NULL,
  `INCHES` varchar(20) DEFAULT NULL,
  `SCREEN_RESOLUTION` varchar(100) DEFAULT NULL,
  `CPU` varchar(100) DEFAULT NULL,
  `RAM` varchar(50) DEFAULT NULL,
  `MEMORY` varchar(50) DEFAULT NULL,
  `GPU` varchar(100) DEFAULT NULL,
  `OS` varchar(50) DEFAULT NULL,
  `WEIGHT` varchar(50) DEFAULT NULL,
  `PRICE` decimal(15,2) DEFAULT NULL,
  ROW_ID INT,
  PRIMARY KEY (`LAP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO LAPT2 
SELECT *,ROW_NUMBER() OVER (PARTITION BY LAP_ID)
FROM LAPT1;


SELECT *
FROM LAPT2
WHERE ROW_ID >1;

-- RESULTS SHOWS THERE IS NO DUPLICATES 

-- 2. FORMATING 

DESCRIBE LAPT2;
SELECT* FROM LAPT2;

SET sql_mode = '';

ALTER TABLE LAPT2
MODIFY INCHES DECIMAL(3,1);

SELECT LEFT(WEIGHT,LOCATE('K',WEIGHT)-1)
FROM LAPT2;

UPDATE LAPT2
SET WEIGHT = LEFT(WEIGHT,LOCATE('K',WEIGHT)-1);

ALTER TABLE LAPT2
CHANGE WEIGHT WEIGHT_KG DECIMAL(3,2);

SELECT LEFT(RAM,LOCATE('G',RAM)-1)
FROM LAPT2;

UPDATE LAPT2
SET RAM = LEFT(RAM,LOCATE('G',RAM)-1);

ALTER TABLE LAPT2
CHANGE RAM RAM_GC INT;

ALTER TABLE LAPT2
RENAME COLUMN RAM_GC TO RAM_GB;

-- 3. DATA NORMALISATION 

SELECT* FROM LAPT2;


SELECT DISTINCT(BRAND)
FROM LAPT2;

SELECT DISTINCT(LAP_TYPE), COUNT(LAP_ID)
FROM LAPT2
GROUP BY LAP_TYPE;

SELECT LEFT(CPU,LOCATE(' ',CPU)),MID(CPU,LOCATE(' ',CPU))
FROM LAPT2;

ALTER TABLE LAPT2
ADD COLUMN CPU_MODEL VARCHAR(100);

UPDATE LAPT2
SET CPU_MODEL = MID(CPU,LOCATE(' ',CPU)),
CPU = LEFT(CPU,LOCATE(' ',CPU));

ALTER TABLE LAPT2
RENAME COLUMN CPU TO CPU_BRAND;

ALTER TABLE LAPT2
MODIFY CPU_MODEL VARCHAR(100) AFTER CPU_BRAND;


SELECT LEFT(MEMORY,LOCATE(' ',MEMORY)-3),MID(MEMORY,LOCATE('B',MEMORY)-1,2),RIGHT(MEMORY,LOCATE(' ',MEMORY))
FROM LAPT2;

ALTER TABLE LAPT2
ADD COLUMN MEMORY_TYPE VARCHAR(50);

ALTER TABLE LAPT2
MODIFY MEMORY_TYPE VARCHAR(50) AFTER MEMORY;

UPDATE LAPT2
SET MEMORY_TYPE = RIGHT(MEMORY,LOCATE(' ',MEMORY)),
MEMORY = LEFT(MEMORY,LOCATE(' ',MEMORY)-3);

UPDATE LAPT2
SET MEMORY_TYPE = 'HDD'
WHERE MEMORY_TYPE LIKE '%HDD%';

UPDATE LAPT2
SET MEMORY_TYPE = 'SSD'
WHERE MEMORY_TYPE LIKE '%SSD%';

UPDATE LAPT2
SET MEMORY_TYPE = 'STORAGE'
WHERE MEMORY_TYPE LIKE '%AGE%';

SELECT DISTINCT(MEMORY_TYPE)
FROM LAPT2;

SELECT DISTINCT(MEMORY)
FROM LAPT2;

ALTER TABLE LAPT2
CHANGE MEMORY MEMORY_SIZE_GB INT;

UPDATE LAPT2
SET MEMORY_SIZE_GB = 1000
WHERE  MEMORY_SIZE_GB = 1;

UPDATE LAPT2
SET MEMORY_SIZE_GB = 2000
WHERE  MEMORY_SIZE_GB = 2;

SELECT DISTINCT(MEMORY_SIZE_GB)
FROM LAPT2;

SELECT LEFT(GPU,LOCATE(' ',GPU)),MID(GPU,LOCATE(' ',GPU))
FROM LAPT2;

ALTER TABLE LAPT2
ADD COLUMN GPU_MODEL VARCHAR(100);

ALTER TABLE LAPT2
MODIFY  GPU_MODEL VARCHAR(100) AFTER GPU;

UPDATE LAPT2
SET  GPU_MODEL= MID(GPU,LOCATE(' ',GPU)),
GPU = LEFT(GPU,LOCATE(' ',GPU));

SELECT* FROM LAPT2;

SELECT DISTINCT(OS)
FROM LAPT2;

-- 4. REMOVE UNNECESSARY COLUMN 

ALTER TABLE LAPT2
DROP COLUMN ROW_ID;

/* END*/ 
